config/routes.rb
Rails.application.routes.draw do

     root 'recipes#index'

    resources :recipes

    get 'signup' => 'users#new', as: :new_user
    post 'signup' => 'users#create', as: :users

    get 'login' => 'sessions#new'
    post 'login' => 'sessions#create'
    get 'logout' => 'sessions#destroy'

    get 'myfavorites' => 'recipes#display_my_favorites'

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :recipes


  #minimal email validation
  #because I agree with this: http://davidcel.is/posts/stop-validating-email-addresses-with-regex/
  validates :email,
  presence: true,
  uniqueness: {case_sensitive: false},
  format: {with: /@/}


  def display_name
    self.email || 'Anon'
  end

  def self.authenticate email, password
    User.find_by_email(email).try(:authenticate, password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :current_user

  def check_auth
    unless current_user
      flash[:warning] = "You must be logged in to access that page."
      redirect_to login_path
    end
  end

  def check_no_auth
    redirect_to root_path if current_user
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def load_model
    return unless params[:id]
    model_name = params[:controller].singularize
    my_model = model_name.classify.safe_constantize
    model_inst = my_model.find params[:id]
    instance_variable_set("@#{model_name}",model_inst)
  end

  def check_ownership
    model_name = params[:controller].singularize
    model_inst = instance_variable_get("@#{model_name}")
    owner = model_inst.user
    if owner.nil? || owner.id != current_user.id
      flash[:danger] = "You cannot change that which does not belong to you."
      redirect_to root_path
    end
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController


    def index
    end


end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

    require 'unirest'

    def index
    end

    def show

        @region = recipe_params[:region]
        @ingredients = recipe_params[:ingredients]
        # @recipeId = recipe_id_param[:recipe_id];

        p recipe_params

        recipesIds = [];
        @allRecipesInfo = [];
        dataSourceUrl = [];
        allDirectionsInfo = [];
        urlStringReplaceSign = '';
        


        response = Unirest.get "https://webknox-recipes.p.mashape.com/recipes/search?cuisine=" + @region + "&number=2&offset=0&query=" + @ingredients,
        headers:{ "X-Mashape-Key" => ENV["RECIPE_API"], "Accept" => "application/json" }

        @data = response.body["results"];
        @baseUri= response.body["baseUri"];

#        adds all recipe ids to the array
        @data.each { |x| recipesIds.push(x["id"])};
#        Now iterate over array to get ingredients

        recipesIds.each do |recipeId|
            response2 = Unirest.get "https://webknox-recipes.p.mashape.com/recipes/" + recipeId.to_s + "/information",
            headers: { "X-Mashape-Key" => ENV["RECIPE_API"], "Accept" => "application/json" }

            @dataSourceUrl = response2.body["sourceUrl"]

            @dataRecipeInfo = response2.body["extendedIngredients"]

            @allRecipesInfo.push(@dataRecipeInfo)
        end
#        render json: @dataRecipeInfo;
#       render json: @allRecipesInfo;
    end

    def display_my_favorites

        @recipes = current_user.recipes.all
        
    end


    def new
    @recipe = Recipe.new

    end


    def create
        @recipe = current_user.recipes.create recipe_id: params[:recipe]
        # @recipe = current_user.recipes.create @recipeId
        if @recipe.persisted?
          flash[:success] = "Your recipe has been added to favorites"
          redirect_to root_path
        else
          flash[:danger] = @recipe.errors.full_messages.uniq.to_sentence
          render :new
        end
      end

        private

       def recipe_params
           params.require(:recipe).permit(:ingredients, :region)
       end

       # def recipe_id_param
       #     params.require(:recipe).permit(:recipe_id)
       # end


    end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action :check_no_auth, except: [:destroy]

  def new
  end

  def create
    user = User.authenticate(params[:user][:email], params[:user][:password])
    if(user)
      session[:user_id] = user.id
      flash[:success] = "You are logged in."
      redirect_to root_path
    else
      flash[:danger] = "Invalid email or password."
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:info] = "You are logged out."
    redirect_to login_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :check_no_auth

  def new
    @user = User.new
  end

  def create
    @user = User.create user_params
    if @user.persisted?
      flash[:success] = "You are signed up. Login below."
      redirect_to login_path
    else
      flash[:danger] = @user.errors.full_messages.uniq.to_sentence
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">World Grub On Rails</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if @current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= @current_user.display_name %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "My Favorites",myfavorites_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out",logout_path %></a></li>
            </ul>
          </li>
        <% else %>
          <li><a href="/signup">Sign Up</a></li>
          <li><a href="/login">Log In</a></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>World Grub on Rails</title>

  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">



  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

</head>
<body>
<%= render partial: 'layouts/nav' %>
<div class="container">
  <div class="row">
    <%= render partial: 'shared/flash' %>
    <%= yield %>
  </div>
</div>



<!-- Latest compiled and minified CSS -->


</body>
</html>

app/views/main/index.html.erb
            <!--images are 1024 x 768-->
            <header class="head" role="banner">
                <a href="" class="logo">
                <img src="assets/worldgrub.png" alt="World Grub">

                </a>

            </header><!-- end header -->

        <div class="top-divider">

        </div>

            <div class="wrap main-content">
            <section class="grid-ingredients">
                <div class="ingredient-input">
                    <h2 class="text-with-padding">Ingredients</h3>
                        <form id="ingredient-input-form">
                            <div>
                                <label>
                                <input type="text" class="ingredient-input-text" id="ingredient-input" size="15">
                                 </label>
                            </div>
                            <input type="submit" class="btn btn-add-ingredient" value="Add">
                            </form>

                            <%= form_for :recipe, html: {class: "recipe_form"} do |f| %>
                              <%= f.text_field :ingredients, class: "ingredient-list-text", id: "ingredient-list", size: "80", :readonly => false  %>

                            <% end %>



                    <label>
                        <div class="region-images">
                            <img src="assets/world-bottom.jpg" class="world-map" alt="Region">
                        </div>

                    </label>
                </div>

                <div class="ingredients-list">



            </section><!-- end product grid -->

            <aside class="sidebar">

            <h2>Regions of the World</h2>

                <ul class="region-list" id="cf7_controls">
                    <li><%= link_to "african", recipe_path("african") %></li>
                    <li><%= link_to "chinese", recipe_path("chinese"), {:controller => :recipes, :action => :show} %></li>
                    <li><%= link_to "japanese", recipe_path("japanese") %></li>
                    <li><%= link_to "korean", recipe_path("korean") %></li>
                    <li><%= link_to "vietnamese", recipe_path("vietnamese") %></li>
                    <li><%= link_to "thai", recipe_path("thai") %></li>
                    <li><%= link_to "indian", recipe_path("indian") %></li>
                    <li><%= link_to "british", recipe_path("british") %></li>
                    <li><%= link_to "irish", recipe_path("irish") %></li>
                    <li><%= link_to "french", recipe_path("french") %></li>
                    <li><%= link_to "italian", recipe_path("italian") %></li>
                    <li><%= link_to "mexican", recipe_path("mexican") %></li>
                    <li><%= link_to "spanish", recipe_path("spanish") %></li>
                    <li><%= link_to "jewish", recipe_path("jewish") %></li>
                    <li><%= link_to "american", recipe_path("american") %></li>
                    <li><%= link_to "cajun", recipe_path("cajun") %></li>
                    <li><%= link_to "southern", recipe_path("southern") %></li>
                    <li><%= link_to "greek", recipe_path("greek") %></li>
                    <li><%= link_to "german", recipe_path("german") %></li>
                    <li><%= link_to "nordic", recipe_path("nordic") %></li>
                    <li><%= link_to "caribbean", recipe_path("caribbean") %></li>
                    <li><%= link_to "vietnamese", recipe_path("vietnamese") %></li>
                </ul>
            </aside>
        </div><!--end wrap -->


        <footer class="foot">


        </footer>

app/views/recipes/_form.html.erb
<%= bootstrap_form_for @recipe do |f| %>
  <%= f.text_field :recipe_id, placeholder: :recipe_id %>
  <%= f.primary "Post" %>
<% end %>

app/views/recipes/display_my_favorites.html.erb
<header class="head" role="banner">
        <%= image_tag("favoritefood.png")%>
</header><!-- end header -->
<h1>My Favorites</h1>

<div id="main-container" class="container">

    <div class="col-md-4" >
    <table class="table table-striped">
    <tbody>
        <h3>Recipe Id</h3>
    <% @recipes.each do |recipe| %>

        <tr>
        <td><%= recipe.recipe_id %>
        <td>
        <span class="glyphicon glyphicon-earphone"></span>
        </td>
        <td>
        <span class="glyphicon glyphicon-trash"></span>
        </td>
        </td>
        </tr>
      <% end %>
    </table>
    </div>
    <div class="col-md-8" >

    </div>
</div>

app/views/recipes/index.html.erb
            <header class="head" role="banner">
            <%= image_tag("worldgrub.jpg")%>

            </header><!-- end header -->

        <div id="main-container" class="container">
            <sdiv class="row">
                <div class="col-md-8" class="font-mega">

                <div class="panel panel-success">
            <div class="panel-heading">
              <h3 class="panel-title">Type an ingredient:</h3>
            </div>
            <div class="panel-body">
              <%= bootstrap_form_for :recipe, url: "/recipes/chinese", :method => :get, html: {class: "recipe_form"} do |f| %>
                              <%= f.text_field :ingredients, class: "ingredient-list-text", id: "ingredient-list", size: "80", :readonly => false  %>
                              <div class="col-md-3">
                              <%= f.radio_button :region, "african" %> African<br />
                              <%= f.radio_button :region, "japanese" %> Japanese<br />
                              </div>
                              <div class="col-md-3">
                              <%= f.radio_button :region, "chinese" %> Chinese<br />
                              <%= f.radio_button :region, "indian" %> Indian<br />
                              </div>
                              <div class="col-md-3">
                              <%= f.radio_button :region, "french" %> French<br />
                              <%= f.radio_button :region, "italian" %> Italian<br />
                              </div>
                              <div class="col-md-3">
                              <%= f.radio_button :region, "mexican" %> Mexican<br />
                              <%= f.radio_button :region, "greek" %> Greek<br />
                              </div>
            </div>
          </div>

                </div>
                <div class="col-md-4">
                <%= f.submit "Submit" %>
                <% end %>

                <div class="page-header">
        <h1>My Regions</h1>
      </div>
      <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
          <li data-target="#carousel-example-generic" data-slide-to="1"></li>
          <li data-target="#carousel-example-generic" data-slide-to="2" class="active"></li>
          <li data-target="#carousel-example-generic" data-slide-to="3"></li>
          <li data-target="#carousel-example-generic" data-slide-to="4"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
          <div class="item active">
            <%= image_tag("korea.jpg")%>
          </div>
          <div class="item">
            <%= image_tag("africa.jpg")%>
          </div>
          <div class="item">
            <%= image_tag("mexico.jpg")%>
          </div>
          <div class="item">
            <%= image_tag("france.jpg")%>
          </div>
          <div class="item">
            <%= image_tag("spain.jpg")%>
          </div>

        </div>
        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>

            </div>

            </div>
        </div><!--end wrap -->

app/views/recipes/new.html.erb
<div class="col-sm-offset-4 col-sm-4">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">Add to favorites</h3>
    </div>
    <div class="panel-body">
      <%= render partial: 'form' %>
    </div>
  </div>
</div>

app/views/recipes/show.html.erb
<header class="head" role="banner">
        <%= image_tag("worldgrub.jpg")%>
</header><!-- end header -->

<div id="main-container" class="container">

    <div class="col-md-4" >
    <table class="table table-striped">
        <tbody>
            <tr>
                    <% @data.each do |item| %>
                     <h1><%= link_to item["id"], recipes_path(:recipe=> item["id"]), :method => :post  %></h1>

                    <h1><%= item["title"] %></h1>
                    <div ><img class="recipe_image" src=<%= @baseUri + item["image"]%> ></div>
                    <% end %>
            </tr>
        </tbody>
    </table>
    </div>
    <div class="col-md-8" >
    <table>
        <tbody>
        <tr>
                
                <% @allRecipesInfo.each do |info| %>
                <h3 class="ingredients">Ingredients </h3>
                <% info.each do |originalString| %>
                
                <h3><%=originalString["originalString"]%></h3>
                <% end %>
                <% end %>
        </tr>
        </tbody>
    </table>
    </div>
</div>

app/views/shared/_flash.html.erb
<% flash.each do |k,v| %>
  <div class="alert alert-<%= k %>">
    <%= v %>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="col-sm-offset-4 col-sm-4" id="new_user_session">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">Sign Up</h3>
    </div>
    <div class="panel-body">
      <%= bootstrap_form_for @user do |f| %>
        <%= f.text_field :email %>
        <%= f.password_field :password %>
        <%= f.primary "Join Now" %>
      <% end %>
    </div>
  </div>
</div>